server:
  port: 10020

spring:
  application:
    name: cloud-grpc-comsumber
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

grpc:
  client:
    cloud-grpc-provider:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
    GLOBAL:
      security:
        client-auth-enabled: false