server:
  port: 8080

grpc:
  server:
    port: 9090
    security:
      enabled: false

spring:
  application:
    name: cloud-grpc-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# actuator management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'